services:
  - type: web
    name: udise-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_AUTH_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_AUTH_EXPIRATION
        value: 1d
      - key: JWT_REFRESH_EXPIRATION
        value: 7d
      - key: EMAIL_ENABLED
        value: "false"

